### ISSUE TITLE
Grapesjs component turn into images

### ISSUE THREAD

**Issue by icube-yuwan** [LiveDuo/destack#77] opened 2023-05-11 05:52 UTC
When using grapesjs editor, everytime I drag & drop component, it will turn into images and got error like this
![image (21)](https://github.com/LiveDuo/destack/assets/102020108/ecae757b-bc22-4468-9d95-bfdbc2c6b2cb)

**Comment by icube-yuwan** [comment] 2023-05-11 05:53
Also when using craft js editor on homepage, I got the same issue as https://github.com/LiveDuo/destack/issues/76#issue-1701967023

**Comment by LiveDuo** [comment] 2023-05-14 18:54
@icube-yuwan Regarding the craft js bug, it's now fixed.

> 
> It was a bug introduced with refactoring [rollup.config.js](https://github.com/LiveDuo/destack/blob/main/lib/rollup.config.js). 
> 
> Just pushed a fix https://github.com/LiveDuo/destack/commit/3969fe731f2d0a990a4abbdea7f6e9aabf6601b3. Should work now.

**Comment by LiveDuo** [comment] 2023-05-14 18:56
I couldn't reproduced the Grapes.js bug on my machine. It's should only happen on a different version of Node.js or a different OS than mine or something else in the environment that I'm not aware of.

Does it happen with `npm i destack` or with `git clone`?

**Closed** 2023-07-01 18:18 UTC
Labels: bug
